#!/bin/bash

apt update -y
apt upgrade -y

apt install expect python3-pip python-pip expect ifmetric wvdial libz-dev libssl-dev libpcap0.8-dev libcurl4-openssl-dev whereami -y

git clone https://github.com/ZerBea/hcxdumptool.git
cd hcxdumptool
make install

cp /root/WiFinder/rpi_setup/reverse_ssh /etc/cron.d/
cp /root/WiFinder/rpi_setup/cnc_cron /etc/cron.d/
cp /root/WiFinder/rpi_setup/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant.conf
cp /root/WiFinder/rpi_setup/wvdial.conf /etc/wvdial.conf
cp /root/WiFinder/rpi_setup/usb_modeswitch.conf /etc/usb_modeswitch.conf

echo "nameserver 1.1.1.1" > /etc/resolv.conf
ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
expect -c 'spawn ssh-copy-id controller@78.130.176.20 -o "StrictHostKeyChecking no"; expect "assword:"; send "toor\r"; interact'


useradd -s /bin/bash -G sudo -m -d /home/rumen rumen
echo -e "toor\ntoor" | passwd rumen
su rumen
ssh-keygen -b 2048 -t rsa -f /home/rumen/.ssh/id_rsa -q -N ""
expect -c 'spawn ssh-copy-id controller@78.130.176.20 -o "StrictHostKeyChecking no"; expect "assword:"; send "toor\r"; interact'

git clone https://github.com/rumendo/WiFinder.git
